// Use the no-auth local testing app with a populated closet.
import { createRequire } from 'node:module'
import assert from 'node:assert/strict'
const require = createRequire(import.meta.url)
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright')
const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH || undefined })
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
const errors = []
page.on('pageerror', e => errors.push(e.message))
try {
  await page.goto('http://127.0.0.1:5174/')
  const hats = page.locator('.wardrobe-section--headwear .rack-pieces')
  const shoes = page.locator('.wardrobe-section--shoes .rack-pieces')
  await hats.locator('button').first().waitFor()
  assert.equal(await hats.locator('button').count(), 24)
  const visible = await hats.evaluate(el => [...el.children].filter(c => c.getBoundingClientRect().right <= el.getBoundingClientRect().right + 1).length)
  assert.equal(visible, 8)
  const label = hats.locator('.wardrobe-piece__name').first()
  await page.mouse.move(0, 0)
  assert.equal(await label.evaluate(el => getComputedStyle(el).opacity), '0')
  await hats.locator('button').first().hover()
  await page.waitForTimeout(160)
  assert.equal(await label.evaluate(el => getComputedStyle(el).opacity), '1')
  await page.mouse.wheel(0, 360)
  await page.waitForTimeout(160)
  assert.ok(await hats.evaluate(el => el.scrollLeft > 300))
  assert.equal(await shoes.evaluate(el => el.scrollLeft), 0)
  await shoes.hover()
  await page.mouse.wheel(420, 0)
  await page.waitForTimeout(160)
  assert.ok(await shoes.evaluate(el => el.scrollLeft > 350))
  await hats.evaluate(el => { el.scrollLeft = el.scrollWidth })
  await hats.hover()
  await page.mouse.wheel(0, 200)
  await page.waitForURL('**/*headwearPage=2*')
  await hats.locator('button').first().waitFor()
  await page.waitForTimeout(600)
  assert.equal(await hats.evaluate(el => el.scrollLeft), 0)
  await page.mouse.wheel(-200, 0)
  await page.waitForURL('**/*headwearPage=1*')
  await hats.locator('button').first().waitFor()
  await page.waitForFunction(() => document.querySelector('.wardrobe-section--headwear .rack-pieces').scrollLeft > 1000)
  await page.goto('http://127.0.0.1:5174/?headwearPage=5')
  await hats.locator('button').first().waitFor()
  assert.equal(await hats.locator('button').count(), 5)
  await page.waitForFunction(() => document.querySelector('[aria-label="Next headwear"]').disabled)
  for (const width of [1440, 900, 390]) {
    await page.setViewportSize({ width, height: 900 })
    await page.goto('http://127.0.0.1:5174/')
    await hats.locator('button').first().waitFor()
    await page.waitForTimeout(300)
    await page.evaluate(() => Promise.all([...document.images].filter(img => img.complete).map(img => img.decode().catch(() => {}))))
    await page.mouse.move(0, 0)
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth && document.documentElement.scrollHeight <= innerHeight))
    await page.screenshot({ path: `/tmp/shelf-scroll-${width}.png` })
  }
  assert.deepEqual(errors, [])
  console.log('PASS: shelf density, hover names, vertical/horizontal wheel isolation, forward/back batch transitions, final batch boundary, responsive layout.')
} finally { await browser.close() }
